#!/usr/bin/env bash
set -ex;

_script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SG_DEVICE="$("${_script_dir}/get_device")"

mkltfs -f -d "${SG_DEVICE}" -s "${TAPE_BARCODE}" -n "${TAPE_NAME}"
sleep 3
