#!/usr/bin/env bash
set -ex;

_script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

mt -f "${DEVICE}" load
BARCODE="$("${_script_dir}/yatm-lto-info" -f "${DEVICE}" | grep 'Barcode' | awk '{print $3}')"
echo "{\"barcode\": \"${BARCODE}\"}" > "${OUT}"
sleep 3
